import { createContext, useContext, useMemo, useState } from 'react';

const LIGHT_COLORS = {
  accent: '#F5C330',
  background: '#DEDEDE',
  border: '#E4E7ED',
  card: '#FFFFFF',
  cardAlt: '#F3F5F8',
  danger: '#C46E6B',
  muted: '#8B93A2',
  primary: '#3159AD',
  primaryDark: '#283F70',
  text: '#273B63',
  textOnPrimary: '#FFFFFF',
};

const DARK_COLORS = {
  accent: '#F5C330',
  background: '#0D1524',
  border: '#31435F',
  card: '#18253A',
  cardAlt: '#22324B',
  danger: '#DF817D',
  muted: '#A9B5C8',
  primary: '#5278C8',
  primaryDark: '#08101E',
  text: '#F4F7FC',
  textOnPrimary: '#FFFFFF',
};

const COPY = {
  it: {
    absent: 'Assente', activate: 'ATTIVA', active: 'attivo', add: 'AGGIUNGI', addCredits: 'Aggiungi crediti', addGame: 'Aggiungi un nuovo gioco', addId: 'AGGIUNGI ID',
    amountToEdit: 'Importo da modificare per', assignPoints: 'Assegna punti a',
    addTime: 'Nuova opzione +', administrator: 'AMMINISTRATORE', adminName: 'Nome Admin', back: 'INDIETRO',
    birthDate: 'Data Nascita', bugs: 'Segnala Bugs', bugsBody: "In questa sezione l’admin dell’app potrà segnalare eventuali bugs riscontrati durante l’utilizzo. Sii più dettagliato possibile per in modo da fornire al team di sviluppo maggiori informazioni.",
    bugsPlaceholder: 'Inserisci in quest’area la tua segnalazione.', cancel: 'Annulla',
    changePassword: 'Cambia Password', chooseGame: 'Scegli il gioco', closedDays: 'GIORNI CHIUSI / FESTIVITÀ',
    choice: 'scelta', choices: 'scelte', codeId: 'Codice ID', confirm: 'Conferma', confirmedTime: 'ORARIO CONFERMATO', confirmPassword: 'Conferma Password', confirmVote: 'Conferma voto',
    confirmedPassword: '✓ Password confermata', contact: 'Contattaci', cover: 'COPERTINA ORIZZONTALE',
    createEvent: 'CREA NUOVO EVENTO', createUser: 'Crea un nuovo utente', credits: 'Crediti',
    credit: 'CREDITO', creditHistory: 'STORICO CREDITO', creditTopUp: 'Ricarica credito',
    currentBalance: 'Saldo attuale', darkMode: 'Dark Mode', days: 'GIORNI',
    close: 'Chiudi', deactivate: 'DISATTIVA', delete: 'ELIMINA', deselect: 'Deseleziona', edit: 'MODIFICA', editProfile: 'MODIFICA PROFILO',
    email: 'Email', emptyDay: 'Nessun evento in questa giornata!', eventConfirmed: 'EVENTO CONFERMATO',
    eventWillTakePlaceAt: "L'evento si farà alle ore",
    emptyUsers: 'Nessun utente\ncreato!\nClicca il simbolo del\n+ per creare un\nnuovo utente', events: 'EVENTI', eventsAugust2026: 'EVENTI AGOSTO 2026',
    expiryOptional: 'Opzionale per gli eventi occasionali', expiryPoll: 'SCADENZA SONDAGGIO',
    filter: 'Filtra', filterSeason: 'Filtra stagione', formatRatio: 'formato consigliato 16:7', gameChoice: 'SCELTA GIOCO', gameIds: 'INSERISCI CODICI ID',
    gameName: 'NOME DEL GIOCO', games: 'GIOCHI', home: 'HOME', hours: 'ORE', hoursBefore: 'ore prima', hoursShort: 'ORE',
    insertAllData: 'Inserisci tutti i dati richiesti', insertBug: 'Inserisci in quest’area la tua segnalazione.', insertCredentials: 'Inserisci username e password',
    insertName: 'Inserisci il nome', insertNewPassword: 'Inserisci la nuova password',
    invalidAdminCredentials: 'Password amministratore non valida', language: 'Lingua', league: 'LEGA', login: 'Login', logout: 'Logout', logo: 'LOGO',
    listParticipants: 'LISTA PARTECIPANTI', minutes: 'MINUTI', modify: 'MODIFICA', monthlyPlanning: 'PROGRAMMAZIONE MENSILE',
    monthlySurveys: 'Sondaggi mensili', modifyVote: 'Modifica voto', moreParticipants: 'Mostra altri partecipanti', multipleChoice: '*Scelta multipla',
    nameSurname: 'Nome Cognome', newGame: 'Nuovo Gioco', next: 'Avanti', nickname: 'nickname/id',
    idMissing: 'ID non inserito', inactive: 'non attivo', noGames: 'Nessun gioco trovato', noParticipants: 'Nessun partecipante trovato',
    noDeadline: 'NESSUNA SCADENZA', noRegisteredParticipants: 'Nessun partecipante registrato', noUsers: 'Nessun utente trovato',
    occasional: 'Occasionale', openClosedCalendar: 'Apri calendario giorni di chiusura', openHistory: 'Apri storico',
    openTicket: 'Apri un Ticket', password: 'Password', passwordChange: 'Cambio Password',
    passwordIntro: 'Seleziona a quale utente\neffettuare il cambio di password', participants: 'PARTECIPANTI',
    phoneOptional: 'Cellulare (Opzionale)', players: 'PLAYERS', points: 'PUNTI', pollDeadlineCustom: 'Personalizzata', present: 'Presente',
    pollTime: 'Orari disponibili', presences: 'PRESENZE', premium: 'PREMIUM', recurring: 'Ricorrente',
    previousMonth: 'Mese precedente', nextMonth: 'Mese successivo', previousWeek: 'Settimana precedente', nextWeek: 'Settimana successiva',
    recoverCredentials: 'Recupero Credenziali', register: 'Registra', report: 'Segnala',
    save: 'SALVA', search: 'Cerca', searchGame: 'Cerca gioco', searchUsername: 'Cerca username', start: 'START', startAt: 'START ORE',
    seconds: 'SECONDI', select: 'Seleziona', selectDates: 'SELEZIONA LE DATE', standardUser: 'UTENTE', subtractCredits: 'Sottrai crediti',
    selectDatesHint: 'Seleziona una o più date dal calendario', selectMonthDays: 'Scegli il mese e uno o più giorni',
    selectYear: 'Seleziona anno', send: 'Invia', settings: 'SETTINGS', signIn: 'Accedi', week: 'SETTIMANA',
    step: 'Passaggio', surveys: 'SONDAGGI', ticket: 'Ticket', ticketBody: 'In questa sezione si ha la possibilità di creare interazioni per futuri sviluppi per gli upgrade dell’app.',
    ticketPlaceholder: 'Inserisci in quest’area la tua richiesta (max 150 caratteri)',
    ticketSent: 'Ticket inviato correttamente', timeByDate: 'ORARI PER DATA',
    timeByDateHint: 'Ogni data può avere più orari', timeout: 'TIMEOUT', total: 'TOTALE',
    totalPlural: 'Totali', updateCredit: 'AGGIORNA CREDITO', users: 'UTENTI',
    version: 'Sidequest App Ver.1.0', votePoll: 'Vota il sondaggio', waiting: 'Attesa', welcome: 'BENVENUTO, NIK', welcomeProfile: 'BENVENUTO', welcomeStart: 'Iniziamo',
    weekdaysHint: 'Puoi selezionare più fasce contemporaneamente', unavailable: 'non disponibile', occupied: 'occupato',
    customizeTime: 'Personalizza orario', customizeDeadline: 'Personalizza scadenza', customDeadlineHours: 'Ore scadenza personalizzate',
    tapCalendarDays: 'Tocca uno o più giorni nel calendario', eventType: 'Tipo evento', newTime: 'Nuovo orario',
    selectedDate: 'Data selezionata', scheduleTime: 'ORARIO', timeUndefined: 'ORARIO DA DEFINIRE', openMenu: 'Apri menu',
    forgotCredentials: 'Non ricordi le tue credenziali?', hideParticipants: 'Nascondi altri partecipanti',
    ticketPlan: 'Il tuo piano prevede:', buyCredits: 'Clicca qui\nper acquistare ulteriori crediti',
    reportBugs: 'Segnala Bugs', reportBugsTitle: 'Segnala Bugs', reportSent: 'Segnalazione inviata correttamente',
    permissionNeeded: 'Permesso necessario', permissionPhotos: 'Consenti a Sidequest di accedere alle immagini per caricare il gioco.',
    latestMovements: 'ULTIMI MOVIMENTI', tournamentEntry: 'Iscrizione torneo', monthlyBonus: 'Bonus mensile',
    eventPurchase: 'Acquisto evento', weeklyTournament: 'Torneo settimanale', promotionalCredit: 'Credito promozionale',
    tableBooking: 'Prenotazione tavolo', today: 'OGGI',
    supportMessage: 'Ciao, purtroppo\nho dimenticato le mie credenziali di accesso.. potresti ricontattarmi per fornirmi un supporto?\ngrazie',
    whatsappError: 'Impossibile aprire WhatsApp', whatsappErrorBody: 'Contatta il numero +39 346 746 0419.', youVoted: 'Hai votato',
  },
  en: {
    absent: 'Absent', activate: 'ACTIVATE', active: 'active', add: 'ADD', addCredits: 'Add credits', addGame: 'Add a new game', addId: 'ADD ID', addTime: 'New option +',
    amountToEdit: 'Amount to edit for', assignPoints: 'Assign points to',
    administrator: 'ADMINISTRATOR', adminName: 'Admin Name', back: 'BACK', birthDate: 'Date of Birth', bugs: 'Report Bugs',
    bugsBody: 'In this section, the app admin can report any bugs encountered while using it. Be as detailed as possible to provide the development team with more information.',
    bugsPlaceholder: 'Enter your report in this area.', cancel: 'Cancel', changePassword: 'Change Password',
    choice: 'choice', choices: 'choices', chooseGame: 'Choose the game', closedDays: 'CLOSED DAYS / HOLIDAYS', codeId: 'ID Code',
    confirm: 'Confirm', confirmedTime: 'CONFIRMED TIME', confirmPassword: 'Confirm Password', confirmedPassword: '✓ Password confirmed', confirmVote: 'Confirm vote',
    contact: 'Contact us', cover: 'HORIZONTAL COVER', createEvent: 'CREATE NEW EVENT',
    createUser: 'Create a new user', credits: 'Credits', credit: 'CREDIT', creditHistory: 'CREDIT HISTORY',
    creditTopUp: 'Credit top-up', currentBalance: 'Current balance', darkMode: 'Dark Mode', days: 'DAYS',
    close: 'Close', deactivate: 'DEACTIVATE', delete: 'DELETE', deselect: 'Deselect', edit: 'EDIT', editProfile: 'EDIT PROFILE', email: 'Email',
    emptyDay: 'No events on this day!', emptyUsers: 'No users\ncreated!\nTap the + symbol\nto create a\nnew user', eventConfirmed: 'EVENT CONFIRMED',
    eventWillTakePlaceAt: 'The event will take place at', events: 'EVENTS', eventsAugust2026: 'AUGUST 2026 EVENTS', expiryOptional: 'Optional for occasional events',
    expiryPoll: 'POLL DEADLINE', filter: 'Filter', filterSeason: 'Filter season', formatRatio: 'recommended format 16:7', gameChoice: 'CHOOSE GAME',
    gameIds: 'ENTER ID CODES', gameName: 'GAME NAME', games: 'GAMES', home: 'HOME', hours: 'HOURS',
    hoursBefore: 'hours before', hoursShort: 'AT', insertAllData: 'Enter all required information', insertCredentials: 'Enter username and password',
    insertBug: 'Enter your report in this area.', insertName: 'Enter the name',
    insertNewPassword: 'Enter the new password', invalidAdminCredentials: 'Invalid administrator password', language: 'Language', league: 'LEAGUE', login: 'Login',
    logout: 'Logout', logo: 'LOGO', listParticipants: 'PARTICIPANT LIST', minutes: 'MINUTES', modify: 'EDIT', monthlyPlanning: 'MONTHLY SCHEDULE',
    monthlySurveys: 'Monthly polls', modifyVote: 'Edit vote', moreParticipants: 'Show more participants', multipleChoice: '*Multiple choice', nameSurname: 'First and Last Name',
    idMissing: 'ID not entered', inactive: 'inactive', newGame: 'New Game', next: 'Next', nickname: 'nickname/id', noGames: 'No games found',
    noDeadline: 'NO DEADLINE', noParticipants: 'No participants found', noRegisteredParticipants: 'No registered participants',
    noUsers: 'No users found', occasional: 'Occasional', openClosedCalendar: 'Open closed-days calendar', openHistory: 'Open history',
    openTicket: 'Open a Ticket', password: 'Password', passwordChange: 'Change Password',
    passwordIntro: 'Select the user whose\npassword you want to change', participants: 'PARTICIPANTS',
    phoneOptional: 'Phone (Optional)', players: 'PLAYERS', points: 'POINTS', pollDeadlineCustom: 'Custom', present: 'Present',
    pollTime: 'Available times', presences: 'ATTENDANCES', premium: 'PREMIUM', recurring: 'Recurring',
    previousMonth: 'Previous month', nextMonth: 'Next month', previousWeek: 'Previous week', nextWeek: 'Next week',
    recoverCredentials: 'Recover Credentials', register: 'Register', report: 'Report', save: 'SAVE',
    search: 'Search', searchGame: 'Search game', searchUsername: 'Search username', seconds: 'SECONDS', standardUser: 'USER', start: 'START', startAt: 'START AT', subtractCredits: 'Subtract credits',
    select: 'Select', selectDates: 'SELECT DATES', selectDatesHint: 'Select one or more dates from the calendar',
    selectMonthDays: 'Choose the month and one or more days', selectYear: 'Select year', send: 'Send',
    settings: 'SETTINGS', signIn: 'Sign in', step: 'Step', surveys: 'POLLS', ticket: 'Ticket', week: 'WEEK',
    ticketBody: 'In this section you can create requests and interactions for future app upgrades and development.',
    ticketPlaceholder: 'Enter your request here (max 150 characters)', ticketSent: 'Ticket sent successfully',
    timeByDate: 'TIMES BY DATE', timeByDateHint: 'Each date can have multiple times', timeout: 'TIMEOUT',
    total: 'TOTAL', totalPlural: 'Total', updateCredit: 'UPDATE CREDIT', users: 'USERS',
    version: 'Sidequest App Ver.1.0', votePoll: 'Vote in the poll', waiting: 'Pending', welcome: 'WELCOME, NIK', welcomeProfile: 'WELCOME', welcomeStart: 'Get Started',
    weekdaysHint: 'You can select multiple time slots', unavailable: 'unavailable', occupied: 'taken',
    customizeTime: 'Customize time', customizeDeadline: 'Customize deadline', customDeadlineHours: 'Custom deadline hours',
    tapCalendarDays: 'Tap one or more days in the calendar', eventType: 'Event type', newTime: 'New time',
    selectedDate: 'Selected date', scheduleTime: 'TIME', timeUndefined: 'TIME TO BE DECIDED', openMenu: 'Open menu',
    forgotCredentials: 'Forgot your credentials?',
    hideParticipants: 'Hide other participants', ticketPlan: 'Your plan includes:',
    buyCredits: 'Click here\nto purchase additional credits', reportBugs: 'Report Bugs', reportBugsTitle: 'Report Bugs',
    reportSent: 'Report sent successfully', permissionNeeded: 'Permission required',
    permissionPhotos: 'Allow Sidequest to access images to upload the game.',
    latestMovements: 'LATEST TRANSACTIONS', tournamentEntry: 'Tournament entry', monthlyBonus: 'Monthly bonus',
    eventPurchase: 'Event purchase', weeklyTournament: 'Weekly tournament', promotionalCredit: 'Promotional credit',
    tableBooking: 'Table reservation', today: 'TODAY',
    supportMessage: 'Hi, unfortunately\nI forgot my login credentials. Could you contact me to provide support?\nThank you',
    whatsappError: 'Unable to open WhatsApp', whatsappErrorBody: 'Contact +39 346 746 0419.', youVoted: 'You voted',
  },
};

const ThemeContext = createContext({
  colors: LIGHT_COLORS,
  isDark: false,
  language: 'it',
  setLanguage: () => {},
  t: (key) => key,
  toggleTheme: () => {},
});

export function ThemeProvider({ children }) {
  const [isDark, setIsDark] = useState(false);
  const [language, setLanguage] = useState('it');
  const value = useMemo(
    () => ({
      colors: isDark ? DARK_COLORS : LIGHT_COLORS,
      isDark,
      language,
      setLanguage,
      t: (key) => COPY[language]?.[key] ?? COPY.it[key] ?? key,
      toggleTheme: () => setIsDark((current) => !current),
    }),
    [isDark, language],
  );

  return <ThemeContext.Provider value={value}>{children}</ThemeContext.Provider>;
}

export function useAppTheme() {
  return useContext(ThemeContext);
}
